# Generated by Django 4.1.7 on 2023-05-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
