# Generated by Django 4.2.2 on 2023-06-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_document_user_documentcollection_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
