# Generated by Django 4.2.2 on 2023-06-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
