# Generated by Django 4.2.2 on 2023-06-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_document_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='commited',
            field=models.BooleanField(default=False),
        ),
    ]
