# Generated by Django 4.2.2 on 2023-06-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_document_commited'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollection',
            name='description',
            field=models.CharField(max_length=30000, null=True),
        ),
    ]
