# Generated by Django 4.2.2 on 2023-06-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_documentcollection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentcollection',
            name='weights',
        ),
        migrations.CreateModel(
            name='DocumentCollectionTraineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.CharField(null=True)),
                ('population_size', models.IntegerField()),
                ('interation_count', models.IntegerField()),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.documentcollection')),
                ('metrics', models.ManyToManyField(to='base.metric')),
            ],
        ),
    ]
