# Generated by Django 4.2.2 on 2023-06-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_insert_metrics_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentcollectiontraineresult',
            old_name='interation_count',
            new_name='iteration_count',
        ),
    ]
