# Generated by Django 4.2.2 on 2023-06-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_interation_count_documentcollectiontraineresult_iteration_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcollection',
            name='score',
        ),
        migrations.AddField(
            model_name='documentcollectiontraineresult',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
